### ISSUE TITLE
btreeSearch无法正常返回数据

### ISSUE THREAD

**Issue by php-cpm** [zoujingli/ip2region#14]
测试用例1：

$ip = new \Ip2Region();
        $ret = $ip->binarySearch('223.104.111.41');
        print_r($ret);

ret=====
Array
(
    [city_id] => 0
    [region] => 中国|0|河南|郑州|移动
)

测试用例2：

$ip = new \Ip2Region();
        $ret = $ip->btreeSearch('223.104.111.41');
        print_r($ret);

ret=====
(empty)

**Comment by zoujingli** [comment]
去源仓库提交问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月24日(星期四) 下午5:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [zoujingli/ip2region] btreeSearch无法正常返回数据 (Issue #14)





 
测试用例1：
 
$ip = new \Ip2Region();
 $ret = $ip-&gt;binarySearch('223.104.111.41');
 print_r($ret);
 
ret=====
 Array
 (
 [city_id] =&gt; 0
 [region] =&gt; 中国|0|河南|郑州|移动
 )
 
测试用例2：
 
$ip = new \Ip2Region();
 $ret = $ip-&gt;btreeSearch('223.104.111.41');
 print_r($ret);
 
ret=====
 (empty)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
