### ISSUE TITLE
php8.2报错

### ISSUE THREAD

**Issue by linjuchen** [zoujingli/ip2region#19]
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /data/web/api/vendor/zoujingli/ip2region/XdbSearcher.php on line 129

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /data/web/api/vendor/zoujingli/ip2region/XdbSearcher.php on line 129
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /data/web/api/vendor/zoujingli/ip2region/XdbSearcher.php on line 150

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /data/web/api/vendor/zoujingli/ip2region/XdbSearcher.php on line 150

**Comment by zoujingli** [comment]
已经推送 v2.0.4 版本
