### ISSUE TITLE
大神能否改进一下composer加载方式，这个很好用，但是现在引用不方便

### ISSUE THREAD

**Issue by indiboy** [zoujingli/ip2region#8]
多谢。现在start的挺多的。

**Comment by zoujingli** [comment]
希望怎么调整？

**Comment by indiboy** [comment]
调整为psr-4规范 直接use引入

**Comment by zoujingli** [comment]
可以的啊
`use Ip2Region;`
不带空间名

**Comment by indiboy** [comment]
th6引入后没有提示，难道是我编辑器问题

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/86559738-4e1d6800-bf8f-11ea-9c96-6aa6a2e93f97.png)

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/86559762-5ecdde00-bf8f-11ea-8502-c3531f72eba6.png)
![image](https://user-images.githubusercontent.com/4349951/86559777-65f4ec00-bf8f-11ea-8188-d86ed01052d4.png)

**Comment by zoujingli** [comment]
上面是两种方式，事实上都一样

**Comment by indiboy** [comment]
好的，我昨天试一下没有提示，我再试一下，非常感谢。
